param(
    [string]$OutputDir = "papers/meta_learning/benchmark_outputs/stage2_scheduler_benchmark",
    [string[]]$Schedulers = @(
        "uniform",
        "bandit_ucb",
        "ats",
        "bass",
        "asr",
        "gcp_proxy"
    ),
    [int[]]$Seeds = @(0, 1, 2),
    [string[]]$AnchorSchedulers = @("uniform"),
    [int[]]$AnchorSeeds = @(0),
    [int]$Steps = 2000,
    [int]$Support = 16,
    [int]$Query = 16,
    [string]$AttackPool = "clean,downup50,crop,jpeg,blur,msg_app,occlusion",
    [string]$EvalAttackSuite = "clean,jpeg_strong,msg_app_combo,down_up,blur,random_crop,occlusion,geom_warp,train_aug_mix"
)

$ErrorActionPreference = "Stop"

New-Item -ItemType Directory -Force -Path $OutputDir | Out-Null

$rows = @()
foreach ($scheduler in $Schedulers) {
    $schedulerSeeds = $Seeds
    if ($AnchorSchedulers -contains $scheduler) {
        $schedulerSeeds = $AnchorSeeds
    }
    foreach ($seed in $schedulerSeeds) {
        $runId = "scheduler_${scheduler}_seed${seed}_steps${Steps}"
        $runDir = Join-Path $OutputDir $runId
        $rows += [pscustomobject]@{
            run_id            = $runId
            scheduler         = $scheduler
            seed              = $seed
            steps             = $Steps
            n_support         = $Support
            n_query           = $Query
            attack_pool       = $AttackPool
            eval_attack_suite = $EvalAttackSuite
            run_dir           = $runDir
            checkpoint_path   = (Join-Path $runDir "checkpoints/final.pth")
            eval_csv          = (Join-Path $runDir "attack_eval_summary.csv")
            status            = "planned"
        }
    }
}

$manifestPath = Join-Path $OutputDir "scheduler_runs.csv"
$rows | Export-Csv $manifestPath -NoTypeInformation

$notes = @(
    '# Stage 2 Scheduler Benchmark Manifest',
    '',
    'Generated by `scripts\stage2_scheduler_manifest.ps1`.',
    '',
    'Each row fixes the attack pool, meta-training steps, support/query size, and seed.',
    'The intended experiment changes only `scheduler`.',
    'Anchor schedulers use a smaller seed set to avoid spending compute on sanity controls.',
    '',
    'After each run writes `attack_eval_summary.csv` to its `run_dir`, aggregate with:',
    '',
    '```powershell',
    'powershell -ExecutionPolicy Bypass -File scripts\stage2_aggregate_scheduler_benchmark.ps1',
    '```',
    '',
    'Current scheduler set:',
    ''
)
$notes += $Schedulers | ForEach-Object { "- ``$_``" }
$notes += ''
$notes += 'Anchor schedulers:'
$notes += $AnchorSchedulers | ForEach-Object { "- ``$_`` seeds: $($AnchorSeeds -join ', ')" }

$notesPath = Join-Path $OutputDir "README.md"
$notes | Set-Content -Path $notesPath -Encoding UTF8

Write-Host "Wrote Stage 2 scheduler manifest to $manifestPath"
Write-Host "Wrote notes to $notesPath"
