param(
    [string]$OutputDir = "papers/meta_learning/benchmark_outputs/stage2_meta_learning_benchmark",
    [string[]]$MetaAlgorithms = @(
        "fomaml",
        "maml",
        "anil",
        "reptile",
        "matching_net",
        "proto_net",
        "r2d2_ridge"
    ),
    [int[]]$Seeds = @(0),
    [int]$Steps = 2000,
    [int]$Support = 16,
    [int]$Query = 16,
    [string]$Scheduler = "ats",
    [string]$AttackPool = "clean,downup50,crop,jpeg,blur,msg_app,occlusion",
    [string]$EvalAttackSuite = "clean,jpeg_strong,msg_app_combo,down_up,blur,random_crop,occlusion,geom_warp,train_aug_mix"
)

$ErrorActionPreference = "Stop"

New-Item -ItemType Directory -Force -Path $OutputDir | Out-Null

$rows = @()
foreach ($algorithm in $MetaAlgorithms) {
    foreach ($seed in $Seeds) {
        $runId = "meta_${algorithm}_${Scheduler}_seed${seed}_steps${Steps}"
        $runDir = Join-Path $OutputDir $runId
        $rows += [pscustomobject]@{
            run_id            = $runId
            meta_algorithm    = $algorithm
            scheduler         = $Scheduler
            seed              = $seed
            steps             = $Steps
            n_support         = $Support
            n_query           = $Query
            attack_pool       = $AttackPool
            eval_attack_suite = $EvalAttackSuite
            run_dir           = $runDir
            checkpoint_path   = (Join-Path $runDir "checkpoints/final.pth")
            eval_csv          = (Join-Path $runDir "attack_eval_summary.csv")
            status            = "planned"
        }
    }
}

$manifestPath = Join-Path $OutputDir "meta_learning_runs.csv"
$rows | Export-Csv $manifestPath -NoTypeInformation

$notes = @(
    '# Stage 2 Meta-Learning Method Benchmark Manifest',
    '',
    'Generated by `scripts\stage2_meta_learning_manifest.ps1`.',
    '',
    'Each row fixes the attack pool, scheduler, steps, support/query size, and seed.',
    'The intended experiment changes only `meta_algorithm`.',
    'Default scheduler is `ats` to avoid spending extra compute on uniform scheduling.',
    'Override `-Scheduler` after Stage 2 if a different best scheduler should be used.',
    '',
    'Main low-cost baselines:',
    ''
)
$notes += $MetaAlgorithms | ForEach-Object { "- ``$_``" }

$notesPath = Join-Path $OutputDir "README.md"
$notes | Set-Content -Path $notesPath -Encoding UTF8

Write-Host "Wrote Stage 2 meta-learning manifest to $manifestPath"
Write-Host "Wrote notes to $notesPath"
